---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andrei-don/eks-argocd-deployment/
    path: 2048-game
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: game-2048
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true