apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 0-namespace.yaml
  - 1-deployment.yaml
  - 2-service.yaml
  - 3-ingress.yaml

namespace: game-2048
replicas:
  - name: deployment-2048
    count: 3