apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 0-deployment.yaml
  - 1-service.yaml
  - 2-ingress.yaml

namespace: game-2048
replicas:
  - name: deployment-2048
    count: 3