name: Infrastructure deployment workflow

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
    AWS_REGION: "eu-west-1"
    TF_VERSION: "1.9.4"

jobs:
    infra-deployment:
        name: Infra deployment
        runs-on: ubuntu-latest

        steps:
        
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::471112989739:role/eks-playground-role
            aws-region: ${{ env.AWS_REGION }}

            
        - name: Configure Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform init
          run: terraform init

        - name: Terraform plan
          run: terraform plan

        - name: Terraform apply
          run: terraform apply -auto-approve